### ISSUE TITLE
getting 2 errors on start

### ISSUE THREAD

**Issue by dylankilkenny** [MalcolmA/Supreme#3] opened 2017-04-04 07:54 UTC
Hi,
Ive tried starting the solution and recieved 2 errors, im not familliar enough with c# to correct.

`CS1519	Invalid token 'ref' in class, struct, or interface member declaration   Product.cs line 31`

`CS1525	Invalid expression term 'throw'  Product.cs line 38`

Am i missing any packages that you may have? 

Any help appreciated

**Comment by MalcolmA** [comment] 2017-04-04 12:04
Hi,

I cannot reproduce the errors right now because I am not at home in my development environment. Nevertheless I recommend that you just remove the `ref` keyword in `Product.cs` line 31 and if needed in `Product.cs` line 56 too. That should work fine as well.

I can also not understand why `throw` is not accepted at this point. Maybe this error was caused by errors that occured before. If you haven't resolved this error yet, try to edit the Product.cs as follows:

Change the method body of `getArticleID()`, `getSizeID()`, `getReferer()`, `getStyleID()` and `getInnerProduct()` from

`return {var} != null ? {var} : throw(new Exception());` 
to something like 
`if({var} == null) { 
Console.WriteLine("Exception"); return null;
} else { return {var}; }`

Best Regards

**Comment by dylankilkenny** [comment] 2017-04-04 14:14
Thanks for your help. Unfortunately it hasnt fixed the problem, removing `ref` causes more issues. I Also noticed another error the compiler wasnt throwing but intellisense pointed out 

` product.getCookieReference() is inaccessible due to its protection level`

What version c# and .net have you been developing in? I feel as though these errors may be related to visual studio somehow.

**Comment by MalcolmA** [comment] 2017-04-04 15:04
Yeah I thought the same when reading those errors. It is very likely that those errors are caused by your development environment. I used the latest version of Visual Studio 2017 Community and the target framework is the latest .NET 4.5.2.

I can say that I builded, debugged and committed the project without changing a single line of code, so basically it should run.

Tell me if you are still experiencing those issues when building it with the VS version mentioned above. 

Best Regards

**Closed as completed** 2017-04-13 12:44 UTC
